### ISSUE TITLE
Rate limit reached will exit process

### ISSUE THREAD

**Issue by evilbinary** [korandoru/griseo#5]
```bash
(venv-py3) [evil]$griseo 
user << uel表达式获取taskId
Traceback (most recent call last):
  File "/Users/evil/dev/python/venv-py3/bin/griseo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/griseo/__init__.py", line 104, in main
    chat()
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/griseo/__init__.py", line 81, in chat
    ctx.tell(req)
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/griseo/__init__.py", line 57, in tell
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/openai/api_requestor.py", line 683, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-r4VrRY1tDifAxfDFz6XdKXIq on requests per min. Limit: 3 / min. Please try again in 20s. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.
(venv-py3) [evil]$clear

```

**Comment by tisonkun** [comment]
Thanks for your report! I think we should catch the specific `openai.error.RateLimitError` and ignore or wait with backoff.

**Comment by tisonkun** [comment]
Pending to handle with [tenacity](https://tenacity.readthedocs.io/en/latest/). See also https://github.com/openai/openai-cookbook/blob/main/examples/How_to_handle_rate_limits.ipynb.
