### ISSUE TITLE
messages input length too long 

### ISSUE THREAD

**Issue by evilbinary** [korandoru/griseo#7]
```bash
Traceback (most recent call last):
  File "/Users/evil/dev/python/venv-py3/bin/griseo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/griseo/__init__.py", line 114, in main
    chat()
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/griseo/__init__.py", line 91, in chat
    ctx.tell(req)
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/griseo/__init__.py", line 58, in tell
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "/Users/evil/dev/python/venv-py3/lib/python3.11/site-packages/openai/api_requestor.py", line 683, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4115 tokens. Please reduce the length of the messages.

```

**Comment by tisonkun** [comment]
The maximum context limitation comes from OpenAI, which we cannot avoid. But we can swallow the exception and hint users to clear context.

Maybe fine-grained context (history) editing is better, but I don't have time to design and implement it now :)

**Comment by tisonkun** [comment]
FYI - 

* https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb
* https://github.com/openai/openai-cookbook/blob/297c53430cad2d05ba763ab9dca64309cb5091e9/examples/How_to_count_tokens_with_tiktoken.ipynb

> when the reply gets cut off from hitting the maximum token limit (4,096 for gpt-3.5-turbo or 8,192 for gpt-4)
